<?php

use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Form\FormState;

/**
 * @file
 * Contains foreningsmentor.module.
 */

/**
 * Implements template_preprocess_node().
 */
function foreningsmentor_preprocess_node(&$variables) {
  $nodeType = $variables["node"]->getType();

  if ($nodeType == 'child') {
    $variables['journal_form'] = \Drupal::formBuilder()->getForm(\Drupal\foreningsmentor\Form\JournalForm::class, $variables["node"]);
    $variables['activity_form'] = \Drupal::formBuilder()->getForm(\Drupal\foreningsmentor\Form\ActivityForm::class, $variables["node"]);
  }
}

function foreningsmentor_preprocess_field(&$variables, $hook) {
  if ($variables["field_name"] == 'field_contact') {
    foreach ($variables["items"][0]["content"] as &$content) {
      $ref = $content["#referenced_content"];

      $uid = $ref->get('field_user')->target_id;

      if ($uid) {
        $user = \Drupal\user\Entity\User::load($uid);

        $imageUrl = NULL;

        if (isset($user->field_profile_image->entity)) {
          $imageUrl = ImageStyle::load('profile_image')->buildUrl($user->field_profile_image->entity->getFileUri());
        }

        $contact = [
          'name' => $user->get('field_name')->value ?: $user->getDisplayName(),
          'image' => $imageUrl,
          'description' => $user->get('field_public_description')->value,
          'mail' => $user->getEmail(),
          'phone' => $user->get('field_own_mobile')->value,
        ];

        $content['contact'] = $contact;
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function foreningsmentor_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_bulk_operations_confirm_action') {
    $newList = [];

    if (isset($form['list'])) {
      foreach ($form["list"]["#items"] as $username) {
        $newList[] = user_load_by_name($username)->getEmail();
      }

      $form["list"]["#items"] = $newList;

      $tempstore = \Drupal::service('user.private_tempstore')->get('foreningsmentor');
      $tempstore->set('copy_to_clipboard', $newList);
    }

    unset($form["actions"]["submit"]);

    $form["actions"]["copy_to_clipboard"] = [
      '#type' => 'submit',
      '#value' => 'Check',
      //'#submit' => ['_foreningsmentor_copy_to_clipboard'],
      '#ajax' => array(
        'callback' => '_foreningsmentor_copy_to_clipboard',
        'progress' => array(
          'type' => 'throbber',
          'message' => NULL,
        ),
      ),
    ];

    $form['#attached']['library'][] = 'foreningsmentor/copy_to_clipboard';
  }

}

function _foreningsmentor_copy_to_clipboard(array &$form, $form_state) : AjaxResponse {
  $tempstore = \Drupal::service('user.private_tempstore')->get('foreningsmentor');

  $list = $tempstore->get('copy_to_clipboard');
  $tempstore->set('copy_to_clipboard', []);

  $ajax_response = new AjaxResponse();
  $ajax_response->addCommand(new \Drupal\foreningsmentor\Ajax\CopyToClipboardCommand($list));

  return $ajax_response;
}
